/**
 * Wiki Modal
 * Shows auto-generated wiki page for an entity
 */

import { useState, useEffect } from 'react';

interface WikiModalProps {
  entityName: string;
  project: string;
  onClose: () => void;
}

export function WikiModal({ entityName, project, onClose }: WikiModalProps) {
  const [wiki, setWiki] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function generateWiki() {
      try {
        setLoading(true);
        setError(null);

        // For now, generate a simple wiki page client-side
        // TODO: Replace with actual backend wiki generation
        const generatedWiki = generatePlaceholderWiki(entityName);

        // Simulate network delay for realism
        await new Promise(resolve => setTimeout(resolve, 300));

        setWiki(generatedWiki);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to generate wiki');
      } finally {
        setLoading(false);
      }
    }

    generateWiki();
  }, [entityName, project]);

  // Close on Escape key
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleEscape);
    return () => window.removeEventListener('keydown', handleEscape);
  }, [onClose]);

  return (
    <div className="wiki-modal-overlay" onClick={onClose}>
      <div className="wiki-modal-content" onClick={(e) => e.stopPropagation()}>
        <div className="wiki-header">
          <div className="wiki-title">
            <span className="wiki-icon">📖</span>
            <h2>{entityName}</h2>
          </div>
          <button className="wiki-close" onClick={onClose}>
            ✕
          </button>
        </div>

        <div className="wiki-body">
          {loading ? (
            <div className="wiki-loading">
              <div className="spinner"></div>
              <p>Generating wiki page...</p>
            </div>
          ) : error ? (
            <div className="wiki-error">
              <p>⚠️ {error}</p>
            </div>
          ) : (
            <div className="wiki-content">
              <div dangerouslySetInnerHTML={{ __html: markdownToHTML(wiki) }} />
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

/**
 * Generate a placeholder wiki page
 * TODO: Replace with actual backend wiki generation
 */
function generatePlaceholderWiki(entityName: string): string {
  return `# ${entityName}

**Type:** Entity (auto-detected)

## Overview

This is an auto-generated wiki page for **${entityName}**.

## Mentions

This entity has been detected in your writing. As you continue writing and the system processes more of your notes, this page will be enriched with:

- All mentions across your documents
- Relationships to other entities
- Timeline of appearances
- Context and quotes

## Relations

_No relations detected yet. Keep writing to discover connections!_

## Next Steps

- Continue writing to see this page grow
- Manual review will allow you to confirm or edit entity details
- You can add custom notes and attributes

---

*This wiki page was automatically generated by ARES Extraction Engine*
`;
}

/**
 * Simple markdown to HTML converter
 * TODO: Use a proper markdown library (marked, markdown-it, etc.)
 */
function markdownToHTML(markdown: string): string {
  return markdown
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/^- (.*$)/gim, '<li>$1</li>')
    .replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/^(?!<[h|u|l])/gim, '<p>')
    .replace(/(?<![>])$/gim, '</p>');
}
